### ISSUE TITLE
Error Using Allure with Ruby

### ISSUE THREAD

**Issue by justjoehere** [allure-framework/allure-ruby#210]
When I run my suite, After the first step is done, I'm getting a cryptic error
`Could not update fixture, fixture is not started`

env.rb
```
AllureCucumber.configure do |config|
  config.results_directory = './reports'
  config.clean_results_directory = true
  config.logging_level = Logger::INFO
  # these are used for creating links to bugs or test cases where {} is replaced with keys of relevant items
  config.link_tms_pattern = 'https://xxxx.atlassian.net/browse/{}'
  config.link_issue_pattern = 'https://xxxx.atlassian.net/browse/{}'
  config.issue_prefix = 'PI_'
end
```

cucumber.yml

```# Profile to include for most other runs
normal: --no-source --color -p pretty

# Typical selected profiles to run against
default: -p normal -p env_trg -p user_2 --tags 'not @wip and not @broken and not @framework' --format AllureCucumber::CucumberFormatter```

**Comment by andrcuns** [comment]
Can you create some kind of example project to reproduce? Can't really help much otherwise. 

For some reason it looks like it tries to update a `fixture` object, which usually is a before or after hook and it fails to do so, because it was not started.

You could also enable debug logging and see more output, mainly how it is handling hooks and test steps.

**Comment by barte2y** [comment]
I was able to reproduce this issue when implementing Afterstep hooks. In particular, it fails in the following method:
`    def handle_hook_started(hook_step)
      lifecycle.public_send(HOOK_HANDLERS[hook_step.text], cucumber_model.fixture_result(hook_step))
    end
`
When reaching the Afterstep hook, `hook_step.text ` is `Afterstep hook`, which is not included in the `HOOK_HANDLERS`:
`    HOOK_HANDLERS = {
      "Before hook" => :start_prepare_fixture,
      "After hook" => :start_tear_down_fixture
    }.freeze
`

**Comment by andrcuns** [comment]
I see. Thanks @barte2y. I suspect it might not handle afterstep and around hooks correctly.

It actually might be somewhat challanging to properly implement AfterStep hook simply because Allure doesn't have such a concept, only before, after scenario. AfterStep will most likely have to be converted to just a step, not a fixture|hook.

I will try to investigate further how this could be handled.
