### ISSUE TITLE
JRuby Compatibility

### ISSUE THREAD

**Issue by HoudayerPierre** [allure-framework/allure-ruby#469]
Hello i'm looking for compatibility with JRuby
I tried with [JRuby 9.4.0.0](https://www.jruby.org/2022/11/23/jruby-9-4-0-0) (Ruby 3.1.0) and [JRuby 9.3.10.0](https://www.jruby.org/2023/02/01/jruby-9-3-10-0) (Ruby 2.6.0 and stays in sync with C Ruby)
Exemple :
``java -jar jruby-complete-9.4.0.0.jar -S gem install allure-cucumber``
or
``java -jar jruby-complete-9.3.10.0.jar -S gem install allure-cucumber``

I always facing an issue with "Oj" and it's seems to be [not be compatible with JRuby](https://github.com/ohler55/oj/issues/607): 

Is it possible to not use C extensions when installing allure-cucumber ?

**Comment by andrcuns** [comment]
@HoudayerPierre 

I would need to do some comparison testing, maybe it's not worth using `Oj` at all. The original idea was to use it for improved performance because depending on test suite, runs can end up generating a lot of json files.

It's not possible to not use C extensions just for `allure-cucumber` because `Oj` is used in `commons` part of reporter as engine for json file generation.

**Comment by andrcuns** [comment]
`Oj` gem is now optional and will only be used if present in project dependencies but not included by default.
